### ISSUE TITLE
【bug】角色授权时，查询出错

### ISSUE THREAD

**Issue by XilongPei** [XilongPei/Openparts#22]
对一个角色进行授权，在查询框中输入 dashboard（其实是随便什么内容都出错），然后点查询，出错。

**Comment by XilongPei** [comment]
Hibernate: 
    select
        rf.id id,
        rf.version version,
        rf.roleId roleId,
        f.name name,
        p.name pname,
        f.code code 
    from
        tbl_role_function rf      
    left join
        tbl_function f 
            on rf.functionId=f.id      
    left join
        tbl_function p 
            on f.parent_id=p.id      
    where
        (
            name LIKE ?
        ) 
        AND (
            roleId = ?
        ) 
        and f.functype!='0' 
    order by
        f.levelCode desc

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'name' in where clause is ambiguous
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1049)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2840)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2212)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:82)
	... 104 more

**Comment by XilongPei** [comment]
fix a bug, Column 'name' in where clause is ambiguous
commit: https://github.com/XilongPei/Openparts/commit/0e3933fd9a1d62afbda1ab084a75f8a1b82b049c
